const SOURCES=[{country:"BE",path:"belgium-chart",name:"Apple Music Belgium"},{country:"NL",path:"netherlands-chart",name:"NVPI Single Top 100"},{country:"FR",path:"france-chart",name:"French Singles"},{country:"ES",path:"south-chart?country=ES&x=1",name:"Apple Music Spain"},{country:"IT",path:"south-chart?country=IT&x=1",name:"Apple Music Italy"}];
function norm(s){return String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\b(feat|ft|featuring)\b.*$/,"").replace(/[^a-z0-9]/g,"");}
function key(t){return norm(t.title)+"|"+norm(t.artist);}
function calc(e){const p=Math.max(1,e.bestPosition||100);let s=100-Math.min(70,(p-1)*1.55)+(e.countries.length-1)*9;if(e.change>=20)s+=18;else if(e.change>=10)s+=14;else if(e.change>=5)s+=10;else if(e.change>=2)s+=6;else if(e.change>0)s+=3;else if(e.change<0)s+=Math.max(-10,e.change*.7);if(e.direction==="NEW")s+=12;return Math.max(15,Math.min(100,Math.round(s)));}
function cat(t){if(t.direction==="NEW"||t.change>=5)return"BREAKOUT";if(t.score>=85||t.countries.length>=2&&t.score>=78)return"HOT NOW";if(t.score>=68||t.change>=2)return"BREAKOUT";return"RADAR";}
async function load(origin,s){try{const r=await fetch(`${origin}/.netlify/functions/${s.path}${s.path.includes("?")?"&":"?"}v=140`,{cache:"no-store"}),d=await r.json();return{...s,active:r.ok&&d.success&&Array.isArray(d.tracks)&&d.tracks.length>0,tracks:Array.isArray(d.tracks)?d.tracks:[],error:d.error||null};}catch(e){return{...s,active:false,tracks:[],error:e.message};}}
export default async request=>{const origin=new URL(request.url).origin,results=await Promise.all(SOURCES.map(s=>load(origin,s))),map=new Map();
for(const src of results)for(const t of src.tracks.slice(0,100)){const k=key(t);if(!k)continue;let e=map.get(k);if(!e){e={id:k,title:t.title,artist:t.artist,countries:[],positions:{},movements:{},bestPosition:999,lastWeek:null,change:0,direction:null,movement:null,image:t.image||null,url:t.url||null};map.set(k,e)}if(!e.countries.includes(src.country))e.countries.push(src.country);e.positions[src.country]=t.position;e.movements[src.country]=t.movement||null;e.bestPosition=Math.min(e.bestPosition,t.position||999);if(!e.image&&t.image)e.image=t.image;if(!e.url&&t.url)e.url=t.url;if(t.lastWeek!=null&&(e.lastWeek==null||(t.change??0)>e.change)){e.lastWeek=t.lastWeek;e.change=t.change??0;e.direction=t.direction;e.movement=t.movement;}}
let tracks=[...map.values()].map(t=>{const score=calc(t);return{...t,score,category:cat({...t,score}),crossCountry:t.countries.length>=2}}).sort((a,b)=>b.score-a.score||b.countries.length-a.countries.length||a.bestPosition-b.bestPosition).slice(0,100);
const hotNow=tracks.filter(t=>t.category==="HOT NOW"),breakout=tracks.filter(t=>t.category==="BREAKOUT"),chartSources={};for(const r of results)chartSources[r.country.toLowerCase()]={active:r.active,tracksLoaded:r.tracks.length,error:r.error,source:r.name};
return Response.json({version:"14.0",updated:new Date().toISOString(),source:"BE + NL + FR + ES + IT live chart radar",signals:{airplay:{active:false,reason:"Removed unreliable HTML airplay feed"}},chartSources,stats:{candidates:map.size,tracks:tracks.length,hotNow:hotNow.length,breakout:breakout.length,crossCountry:tracks.filter(t=>t.crossCountry).length},tracks,hotNow,breakout},{headers:{"cache-control":"public, max-age=60, s-maxage=1800"}});};